# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/vivalto3gvn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/vivalto3gvn/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/vivalto3gvn/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/vivalto3gvn/proprietary/bin/bmgr:system/bin/bmgr \
    vendor/samsung/vivalto3gvn/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/vivalto3gvn/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/vivalto3gvn/proprietary/bin/slog:system/bin/slog \
    vendor/samsung/vivalto3gvn/proprietary/bin/engpc:system/bin/engpc \
    vendor/samsung/vivalto3gvn/proprietary/bin/smd:system/bin/smd \
    vendor/samsung/vivalto3gvn/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/vivalto3gvn/proprietary/bin/ddexe:system/bin/ddexe \
    vendor/samsung/vivalto3gvn/proprietary/bin/connfwexe:system/bin/connfwexe \
    vendor/samsung/vivalto3gvn/proprietary/bin/createsystemfile:system/bin/createsystemfile \
    vendor/samsung/vivalto3gvn/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/vivalto3gvn/proprietary/etc/slog.conf:system/etc/slog.conf \
    vendor/samsung/vivalto3gvn/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libSamsungPkcs11Wrapper.so:system/lib/libSamsungPkcs11Wrapper.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    vendor/samsung/vivalto3gvn/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/vivalto3gvn/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/vivalto3gvn/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/vivalto3gvn/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsprd_agps_agent.so:system/lib/libsprd_agps_agent.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/gralloc.scx15.so:system/lib/hw/gralloc.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/hwcomposer.scx15.so:system/lib/hw/hwcomposer.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/etc/audio_hw.xml:system/etc/audio_hw.xml \
    vendor/samsung/vivalto3gvn/proprietary/etc/audio_para:system/etc/audio_para \
    vendor/samsung/vivalto3gvn/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/vivalto3gvn/proprietary/etc/codec_pga.xml:system/etc/codec_pga.xml \
    vendor/samsung/vivalto3gvn/proprietary/etc/tiny_hw.xml:system/etc/tiny_hw.xml \
    vendor/samsung/vivalto3gvn/proprietary/bin/tinymix:system/bin/tinymix \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/audio.primary.scx15.so:system/lib/hw/audio.primary.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libnvexchange.so:system/lib/libnvexchange.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libdumpdata.so:system/lib/libdumpdata.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsonivox.so:system/lib/libsonivox.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_SoundAlive_ver118t.so:system/lib/lib_SoundAlive_ver118t.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_SamsungRec_V03011b.so:system/lib/lib_SamsungRec_V03011b.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/vivalto3gvn/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/vivalto3gvn/proprietary/lib/libbt-hci.so:system/lib/libbt-hci.so \
    vendor/samsung/vivalto3gvn/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/vivalto3gvn/proprietary/vendor/firmware/BCM4343A0_001.001.034.0038.0090_ORC_Vivalto-3G_3MC.hcd:system/vendor/firmware/BCM4343A0_001.001.034.0038.0090_ORC_Vivalto-3G_3MC.hcd \
    vendor/samsung/vivalto3gvn/proprietary/etc/nvitem_td.cfg:system/etc/nvitem_td.cfg \
    vendor/samsung/vivalto3gvn/proprietary/etc/nvitem_w.cfg:system/etc/nvitem_w.cfg \
    vendor/samsung/vivalto3gvn/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/vivalto3gvn/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/vivalto3gvn/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/vivalto3gvn/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/vivalto3gvn/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/samsung/vivalto3gvn/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/samsung/vivalto3gvn/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/vivalto3gvn/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/vivalto3gvn/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libmorpho_facesolid.so:system/lib/libmorpho_facesolid.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/camera.scx15.so:system/lib/hw/camera.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/camera2.scx15.so:system/lib/hw/camera2.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/sprd_gsp.scx15.so:system/lib/hw/sprd_gsp.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/sensors.scx15.so:system/lib/hw/sensors.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/vivalto3gvn/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_soft_mpeg4dec.so:system/lib/libstagefright_sprd_soft_mpeg4dec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_soft_h264dec.so:system/lib/libstagefright_sprd_soft_h264dec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_mpeg4dec.so:system/lib/libstagefright_sprd_mpeg4dec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_mpeg4enc.so:system/lib/libstagefright_sprd_mpeg4enc.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_h264dec.so:system/lib/libstagefright_sprd_h264dec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_h264enc.so:system/lib/libstagefright_sprd_h264enc.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_vpxdec.so:system/lib/libstagefright_sprd_vpxdec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_soft_mjpgdec.so:system/lib/libstagefright_soft_mjpgdec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_soft_imaadpcmdec.so:system/lib/libstagefright_soft_imaadpcmdec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_aacdec.so:system/lib/libstagefright_sprd_aacdec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_mp3dec.so:system/lib/libstagefright_sprd_mp3dec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_aacdec_sprd.so:system/lib/libomx_aacdec_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomafldrm.so:system/lib/libomafldrm.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/drm/libomaplugin.so:system/lib/drm/libomaplugin.so \
    vendor/samsung/vivalto3gvn/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/vivalto3gvn/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/vivalto3gvn/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/vivalto3gvn/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/vivalto3gvn/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/vivalto3gvn/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg
